{
  "chapterId": "chapter_001",
  "chapterTitle": "Chương 1980: Toàn bộ cùng chung số phận (Thượng)",
  "content": [
    "Kim Lân Đại Tôn nghe vậy, sắc mặt chợt biến.",
    "Trong trận quyết chiến cuối cùng tại Hỗn Nguyên Châu, nguyên nhân căn bản khiến đại quân nhân tộc tan tác chính là vạn quân của họ đều mang theo huyết dịch từ Thiên Khanh Viễn Cổ.",
    "Loại huyết dịch này, chỉ cần nhân tộc chạm vào một chút, lập tức sẽ hóa thành Cự Nhân ngay tại chỗ.",
    "Giờ đây, các Cự Nhân lại dùng thủ đoạn này.",
    "Hắn vội vàng quát lớn: “Cẩn thận ô huyết!”",
    "Đại quân Trung Thổ đang giao chiến, trong lòng chợt rùng mình, khí thế đang hừng hực bỗng chốc trở nên rụt rè khi đối mặt với Viễn Cổ Cự Nhân.",
    "Những ô huyết kia, chỉ cần chạm vào một chút thôi cũng sẽ bị hắc hóa thành Cự Nhân!",
    "Ngay cả năm vị Đại Tôn đang tung hoành ngang dọc cũng phải ném chuột sợ vỡ bình.",
    "Khí thế đại quân Trung Thổ vừa chững lại, Cự Nhân Vương và Tu La Vương liền phản công.",
    "“Vu Phó Cung Chủ, cẩn thận!” Thử Bất Hư tinh tường nhận ra, một Cự Nhân Vương đang ẩn mình tiếp cận Vu Phó Cung Chủ.",
    "Vu Phó Cung Chủ tim đập thình thịch, vội vàng né tránh.",
    "Vừa kịp rời đi, phía sau nàng hiện ra Ẩn Chi Cự Nhân Vương, một chiếc lưỡi dài xuyên thủng vị trí nàng vừa đứng.",
    "Một kế không thành, Ẩn Chi Cự Nhân Vương quả quyết mở ống trúc trong tay, tung vãi về phía Vu Phó Cung Chủ.",
    "Vu Phó Cung Chủ đồng tử co rút, vội vàng né tránh.",
    "Tuy nhiên, trong ống trúc lại trống rỗng.",
    "Ẩn Chi Cự Nhân Vương cười cợt: “Lừa ngươi đó!”",
    "Vu Phó Cung Chủ tức giận, đang chuẩn bị phản kích, bên cạnh lại xông ra một Phong Chi Cự Nhân Vương, ôm một ống trúc vãi tới.",
    "Thời cơ nó đánh lén quá chuẩn xác, Vu Phó Cung Chủ không kịp né tránh.",
    "Chỉ theo bản năng vung tay áo chống đỡ.",
    "Thế nhưng, trong ống trúc này lại thực sự đổ ra ô huyết.",
    "Xuy xuy!",
    "Ô huyết vương vãi lên người Vu Phó Cung Chủ, chỉ trong hơi thở, nàng đã kêu lên một tiếng thảm thiết, thân thể cấp tốc bành trướng, nhanh chóng hóa thân thành một Cự Nhân Vương!",
    "Sau đó, nàng mất hết lý trí, điên cuồng tấn công xung quanh.",
    "Thì ra, vì huyết thủy của Thiên Khanh Viễn Cổ bị Lăng Hư Tử phá hủy, khiến bọn chúng không thể thu thập đủ số lượng dự kiến.",
    "Vì vậy, một số ống trúc có ô huyết, một số thì không.",
    "Nhưng điều này lại càng khiến đại quân Trung Thổ rối loạn phương tấc.",
    "Các Cự Nhân vừa rút ống trúc ra, hư chiêu một cái đã buộc cường giả Trung Thổ phải né tránh, và điều này đã tạo cơ hội tuyệt vời cho kẻ địch phối hợp đánh lén.",
    "Chỉ trong vài chục hơi thở, đã có hơn mười vị Hóa Thần cảnh của Trung Thổ bị chuyển hóa thành Cự Nhân, hoành hành phá hoại.",
    "Còn có mấy vị Hóa Thần cảnh khác thì bị đánh lén chết ngay tại chỗ.",
    "Tình thế của phe Trung Thổ chuyển biến xấu nhanh chóng!",
    "Đại quân bị buộc phải liên tục lùi lại, thương vong cũng tăng lên nhanh chóng.",
    "Trong mắt Chân Ngôn lóe lên hàn quang, nàng bay vút lên không trung, phát động lĩnh vực quét ngang toàn cảnh, nói:",
    "“Ai có chân ô huyết?”",
    "Trong tiếng chất vấn, khoảng hơn mười Cự Nhân Vương có tu vi dưới nàng, không thể kiểm soát mà mở miệng.",
    "“Ta!”",
    "Đây là lĩnh vực thứ ba mà nàng đã lĩnh ngộ.",
    "Cưỡng Chế Chân Ngôn!",
    "Lĩnh vực đầu tiên của nàng cũng là nói chân ngôn, nhưng đối phương có thể chọn im lặng không trả lời.",
    "Lĩnh vực thứ ba, thì là cưỡng chế nói chân ngôn, không cho phép đối phương im lặng!",
    "Thế yếu của đại quân Trung Thổ hơi chấn động.",
    "Chỉ cần tránh những Cự Nhân Vương có ô huyết, những Cự Nhân Vương khác sẽ không thể giương oai hù dọa nữa.",
    "Mặc dù vẫn còn khó khăn, nhưng ít nhất sẽ không bị bọn chúng dắt mũi.",
    "Đại quân đang lùi lại chậm dần, thương vong cũng giảm bớt, thậm chí bắt đầu phản công tiêu diệt những Cự Nhân Vương không có ô huyết.",
    "Điều này khiến các Cự Nhân vô cùng tức giận.",
    "Mấy vị Tu La Vương khóa chặt nàng, đồng loạt vây giết tới.",
    "Chân Ngôn Tôn Giả như lâm đại địch, cùng bọn chúng liều mạng chém giết, và ngay lúc trận chiến đang gay cấn nhất.",
    "Vị Phong Chi Cự Nhân Vương đã đánh lén Vu Phó Cung Chủ, lại làm theo cách cũ, nhanh như điện chớp tung ô huyết trong ống trúc về phía nàng.",
    "Mấy vị Tu La Vương càng thừa thế xông lên, bức Chân Ngôn Tôn Giả không thể né tránh.",
    "Đồng tử Chân Ngôn Tôn Giả co rút lại!",
    "Nhưng ngay vào thời khắc nguy cấp vạn phần, một bóng hình nhanh như chớp, vẫy đôi cánh trắng như tuyết, lướt tới.",
    "Là Hạ Triều Ca!",
    "Nàng toàn thân đẫm máu, trên người còn có những vết thương kinh hoàng, không thể lành lại.",
    "Trước ngực, bụng, đều có huyết dịch thiên sứ màu cửu sắc.",
    "Phát hiện Chân Ngôn Tôn Giả gặp nguy, nàng đã chọn lộ thân phận Thiên Sứ tộc để đến cứu viện.",
    "Chân Ngôn Tôn Giả là nữ nhân của sư thúc.",
    "Nếu nàng chết, sư thúc sẽ rất đau lòng.",
    "Nàng há miệng phun ra, một viên nội đan trắng như tuyết bay ra, phóng thích thánh quang rực rỡ vô cùng.",
    "Chiếu rọi lên các Cự Nhân Vương xung quanh, khiến chúng toàn thân bốc khói đen, miệng phát ra tiếng gầm đau đớn như bị thiêu đốt.",
    "Ô huyết vãi tới cũng bị thánh quang thiêu cháy ngay tại chỗ.",
    "“Hạ Triều Ca?” Chân Ngôn Tôn Giả ngẩn người.",
    "Nàng vẻ mặt không thể tin được, vị nữ sư điệt của Giang Phàm này, lại là một Thiên Sứ tộc!",
    "Phong Chi Cự Nhân Vương đánh lén thất bại kinh ngạc nói: “Thánh đan chỉ Thiên Sứ quý tộc mới có?”",
    "Ngay sau đó, vẻ mặt nó trở nên dữ tợn: “Nghe nói Thiên Sứ quý tộc ăn vào, càng ngon hơn!”",
    "Xoẹt!",
    "Thân ảnh nó biến mất trong không trung.",
    "Một chiếc lưỡi dài nhanh đến không thể tin được, xuyên thủng không gian, bắn thẳng vào mặt Hạ Triều Ca.",
    "Đây là một Tam Tinh Phong Chi Cự Nhân Vương, vốn đã tốc độ tuyệt luân, thêm vào đó chiếc lưỡi nhanh như điện chớp.",
    "Cú đánh này, ngay cả Chân Ngôn Tôn Giả cũng không kịp phản ứng.",
    "Hạ Triều Ca chỉ cảm thấy một luồng gió tanh tưởi ập vào mặt, tầm nhìn bị một chiếc lưỡi dài đỏ tươi chiếm trọn.",
    "Nếu không có gì bất ngờ, nàng sẽ bị một lưỡi xuyên thủng đầu.",
    "Cứ thế mà chết sao?",
    "Trong đầu nàng chỉ kịp lóe lên một ý nghĩ, rồi trước mắt chìm vào bóng tối.",
    "Thế nhưng, không có cảm giác đau đớn truyền đến.",
    "Ngược lại, toàn bộ cơ thể nàng lại áp sát vào một vật thể rắn chắc ấm áp.",
    "Nàng ngẩng đầu ra sau, lúc này mới phát hiện, đó là bóng lưng của một người!",
    "Gầy gò nhưng mạnh mẽ, cao lớn và thanh thoát.",
    "Chỉ nhìn một cái, nàng đã nhận ra, kinh hô thành tiếng: “Sư thúc?”",
    "Nàng gần như không thể tin vào mắt mình.",
    "Sư thúc không phải đang ở Trung Thổ sao?",
    "Giang Phàm một tay nắm lấy lưỡi dài của Phong Chi Cự Nhân Vương, dùng thân thể che chắn Hạ Triều Ca và Chân Ngôn Tôn Giả phía sau.",
    "Không quay đầu lại nói: “Lần sau đừng làm chuyện ngu ngốc nữa.”",
    "Dứt lời, lòng bàn tay đột nhiên bốc lên ngọn lửa dung hợp của Thánh Hỏa và Âm Hỏa.",
    "Xuy xuy một tiếng, ngọn lửa theo lưỡi dài đột ngột cháy lan lên người Phong Chi Cự Nhân Vương.",
    "Tam Tinh Cự Nhân Vương này, thậm chí còn không kịp kêu thảm, đã từ lưỡi dài đến đầu rồi đến thân thể, toàn bộ bị thiêu thành tro bụi.",
    "Vai Hạ Triều Ca thả lỏng, theo bản năng tựa vào lưng Giang Phàm.",
    "Khoảnh khắc nhận ra bóng lưng Giang Phàm, nàng cảm thấy an toàn lạ thường, trái tim căng thẳng bấy lâu đột nhiên buông xuống.",
    "Có Giang Phàm ở đây, nàng có thể không cần lo lắng nữa.",
    "Giang Phàm lại cứng đờ người, thẳng lưng, lộ ra một tia dị sắc, nói:",
    "“Triều Ca, cùng Chân Ngôn lùi lại.”",
    "Hạ Triều Ca hoàn hồn, cúi đầu nhìn xuống, lúc này mới phát hiện ngực mình đang tựa vào lưng Giang Phàm.",
    "Nơi nhô cao nhất, bị ép dẹt.",
    "Nàng khuôn mặt xinh đẹp lập tức đỏ bừng, vội vàng lùi lại, còn cẩn thận liếc nhìn sắc mặt Chân Ngôn Tôn Giả.",
    "Phát hiện nàng không lộ ra vẻ dị thường, mới thầm thở phào nhẹ nhõm.",
    "Dù vậy, vẫn đầy vẻ chột dạ: “Chân Ngôn sư thúc nương, chúng ta… đi chỗ khác đi.”",
    "Chân Ngôn Tôn Giả đang mừng rỡ nhìn chằm chằm bóng lưng Giang Phàm.",
    "Cũng như Hạ Triều Ca, khoảnh khắc nhận ra bóng lưng Giang Phàm, nàng cảm thấy an tâm hơn bao giờ hết.",
    "Dường như cảnh tuyệt vọng trước mắt, không còn là vấn đề nữa.",
    "“Phu quân, chàng một mình ứng phó được không?”",
    "Nàng nhìn quanh, không chỉ có bốn vị Tu La Vương vừa vây công nàng.",
    "Xa xa còn có mấy vị Tu La Vương và Cự Nhân Vương đang cấp tốc lao tới.",
    "Trong đó có hai Cự Nhân Vương sở hữu ô huyết!",
    "Giang Phàm quét mắt nhìn chiến trường, nhìn những thi thể nhân tộc la liệt khắp nơi, đôi mắt lập tức như hầm băng, tỏa ra hàn khí lạnh lẽo:",
    "“Các ngươi! Tất cả hãy chôn cùng đi!”"
  ],
  "metadata": {
    "extractedAt": "2025-10-29T10:13:19.366Z",
    "totalParagraphs": 103,
    "wordCount": 1720
  }
}